version: '3.8'
services:
  product-service:
    build: ./backend/product-service
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
  order-service:
    build: ./backend/order-service
    ports:
      - '3002:3002'
    environment:
      - NODE_ENV=development
    depends_on:
      - product-service
  frontend:
    build: ./frontend/dynamic-form-app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    depends_on:
      - product-service
      - order-service
